### ISSUE TITLE
Histograms stored in samples take too much memory during long runs

### ISSUE THREAD

**Issue by vponomaryov** [pkolaczk/latte#67]
![Screenshot from 2024-03-29 14-19-56](https://github.com/pkolaczk/latte/assets/3796058/5f18e80a-1b77-4c5d-b45d-1ab93a07467a)
On the screenshot above we see memory utilization of 2 nodes which are used for running latte.
Memory utilization grew up to 10Gb for 3 hours of uptime on each of the nodes.

Debugged a bit locally and observed that memory leaks happen during each event of sampling.
My observation is that memory utilization is directly related to the made operations during a sampling period.

**Comment by pkolaczk** [comment]
Latte collects some data (summaries) in memory and processes them afterwards; so some memory growth is expected. However if it is 10 GB, that's a lot. My first guess would be histograms...

**Comment by vponomaryov** [comment]
> Latte collects some data (summaries) in memory and processes them afterwards; so some memory growth is expected. However if it is 10 GB, that's a lot. My first guess would be histograms...

The root cause is the constantly growing number of stored samples which then gets used for the report generation.
And yes, those include histograms.

So, the proper solution, I think, would be to process samples on the go and store only the processed single summary result which get updated with each sampling step.

**Comment by pkolaczk** [comment]
The histograms in the samples are compressed and then stored in the report for future use, e.g. for producing HdrHistogram logs (`latte hdr` command). So I think this needs a user-facing change. Instead of saving the histograms to the report the option for producing HDR logs should be tied directly to `run` and the histograms should be optionally streamed to a file while running. This would have an additional benefit of making the reports smaller and faster to load, which is now even more important after I added the `latte list` command.
